'use client'

import { jsPDF } from 'jspdf'
import type { ReportSection } from '@/lib/supabase/queries/reports'

export interface PeaExportOptions {
  title: string
  preparedFor: string
  siteCode: string
  version: number
  date: string
  sections: ReportSection[]
  appendices: string[]
}

/**
 * Strip markdown formatting to plain text for PDF rendering.
 * Preserves line breaks and list structure.
 */
function stripMarkdown(md: string): string {
  return (
    md
      // Remove bold/italic markers
      .replace(/\*\*\*(.*?)\*\*\*/g, '$1')
      .replace(/\*\*(.*?)\*\*/g, '$1')
      .replace(/\*(.*?)\*/g, '$1')
      .replace(/__(.*?)__/g, '$1')
      // Remove headers (keep text)
      .replace(/^#{1,6}\s+/gm, '')
      // Remove link syntax, keep text
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      // Remove inline code backticks
      .replace(/`([^`]+)`/g, '$1')
      // Clean up table formatting — convert to simple text
      .replace(/\|/g, '  ')
      .replace(/^[\s-]+$/gm, '')
      // Trim extra whitespace
      .replace(/\n{3,}/g, '\n\n')
      .trim()
  )
}

/**
 * Generate a PEA report PDF using jsPDF.
 */
export function generatePeaPdf(options: PeaExportOptions): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const contentWidth = pageWidth - margin * 2
  const lineHeight = 5
  const footerY = pageHeight - 15

  let currentPage = 1

  // Helper: add footer to current page
  const addFooter = () => {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(128, 128, 128)
    doc.line(margin, footerY - 3, pageWidth - margin, footerY - 3)
    doc.text(`${options.siteCode} — ${options.title}`, margin, footerY)
    doc.text(`Page ${currentPage}`, pageWidth - margin, footerY, { align: 'right' })
    doc.setTextColor(0, 0, 0)
  }

  // Helper: add new page with footer
  const addPage = () => {
    addFooter()
    doc.addPage()
    currentPage++
    return margin
  }

  // Helper: write wrapped text, auto-paginating
  const writeText = (
    text: string,
    startY: number,
    opts?: { fontSize?: number; fontStyle?: 'normal' | 'bold' | 'italic' }
  ): number => {
    const fontSize = opts?.fontSize || 10
    const fontStyle = opts?.fontStyle || 'normal'
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', fontStyle)

    const lines = doc.splitTextToSize(text, contentWidth) as string[]
    let y = startY

    for (const line of lines) {
      if (y + lineHeight > footerY - 5) {
        y = addPage()
      }
      doc.text(line, margin, y)
      y += lineHeight
    }

    return y
  }

  // ===== COVER PAGE =====
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(44, 82, 52) // Green
  doc.text('PRELIMINARY ECOLOGICAL APPRAISAL', pageWidth / 2, 60, { align: 'center' })

  doc.setFontSize(20)
  doc.setTextColor(0, 0, 0)
  const titleLines = doc.splitTextToSize(options.title, contentWidth - 20) as string[]
  let titleY = 80
  for (const line of titleLines) {
    doc.text(line, pageWidth / 2, titleY, { align: 'center' })
    titleY += 10
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'normal')
  const coverDetails = [
    { label: 'Prepared For', value: options.preparedFor || 'Client' },
    { label: 'Site Reference', value: options.siteCode },
    { label: 'Version', value: `${options.version}` },
    { label: 'Date', value: options.date },
  ]

  let coverY = titleY + 20
  for (const detail of coverDetails) {
    doc.setFont('helvetica', 'bold')
    doc.text(`${detail.label}:`, pageWidth / 2 - 30, coverY)
    doc.setFont('helvetica', 'normal')
    doc.text(detail.value, pageWidth / 2 + 20, coverY)
    coverY += 8
  }

  doc.setFontSize(9)
  doc.setTextColor(128, 128, 128)
  doc.text('Generated by Dulra Ecological Platform', pageWidth / 2, pageHeight - 30, {
    align: 'center',
  })
  doc.setTextColor(0, 0, 0)

  // ===== TABLE OF CONTENTS =====
  addFooter()
  doc.addPage()
  currentPage++

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Table of Contents', margin, margin + 10)

  let tocY = margin + 25
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  const contentSections = options.sections.filter((s) => s.content)
  for (let i = 0; i < contentSections.length; i++) {
    doc.text(`${i + 1}. ${contentSections[i].title}`, margin + 5, tocY)
    tocY += 7
  }

  if (options.appendices.length > 0) {
    tocY += 5
    doc.setFont('helvetica', 'bold')
    doc.text('Appendices', margin + 5, tocY)
    tocY += 7
    doc.setFont('helvetica', 'normal')
    const appendixLabels: Record<string, string> = {
      habitat_map: 'Habitat Map',
      species_list: 'Species List',
      photographs: 'Site Photographs',
      survey_datasheets: 'Survey Datasheets',
      desk_study_data: 'Desk Study Data',
      legislation: 'Legislation References',
    }
    const letters = 'ABCDEFGHIJ'
    for (let i = 0; i < options.appendices.length; i++) {
      const label = appendixLabels[options.appendices[i]] || options.appendices[i]
      doc.text(`Appendix ${letters[i] || i + 1}: ${label}`, margin + 10, tocY)
      tocY += 7
    }
  }

  // ===== REPORT SECTIONS =====
  for (const section of contentSections) {
    let y = addPage()

    // Section title
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(44, 82, 52)
    doc.text(section.title, margin, y)
    doc.setTextColor(0, 0, 0)
    y += 10

    // Section content — strip markdown and write as plain text
    const plainText = stripMarkdown(section.content)
    const paragraphs = plainText.split('\n\n')

    for (const paragraph of paragraphs) {
      const trimmed = paragraph.trim()
      if (!trimmed) continue

      // Check if it's a list item or a heading-like line
      const lines = trimmed.split('\n')
      for (const line of lines) {
        const stripped = line.trim()
        if (!stripped) continue

        // Detect bullet points
        if (stripped.startsWith('- ') || stripped.startsWith('* ') || /^\d+\.\s/.test(stripped)) {
          y = writeText(`  ${stripped}`, y, { fontSize: 10 })
        } else {
          y = writeText(stripped, y, { fontSize: 10 })
        }
      }
      y += 3 // Paragraph spacing
    }
  }

  // ===== APPENDICES PLACEHOLDER =====
  if (options.appendices.length > 0) {
    let y = addPage()

    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(44, 82, 52)
    doc.text('Appendices', margin, y)
    doc.setTextColor(0, 0, 0)
    y += 10

    const appendixLabels: Record<string, string> = {
      habitat_map: 'Habitat Map',
      species_list: 'Species List',
      photographs: 'Site Photographs',
      survey_datasheets: 'Survey Datasheets',
      desk_study_data: 'Desk Study Data',
      legislation: 'Legislation References',
    }
    const letters = 'ABCDEFGHIJ'

    for (let i = 0; i < options.appendices.length; i++) {
      const label = appendixLabels[options.appendices[i]] || options.appendices[i]
      y = writeText(`Appendix ${letters[i] || i + 1}: ${label}`, y, {
        fontSize: 11,
        fontStyle: 'bold',
      })
      y = writeText('[Content to be inserted]', y, { fontSize: 10 })
      y += 5
    }
  }

  // Add footer to last page
  addFooter()

  return doc
}

/**
 * Generate a PEA report as HTML string.
 * Can also be used for DOCX export (saved as .doc with HTML content).
 */
export function generatePeaHtml(options: PeaExportOptions): string {
  const contentSections = options.sections.filter((s) => s.content)

  const tocHtml = contentSections
    .map((s, i) => `<li><a href="#section-${i}">${s.title}</a></li>`)
    .join('\n')

  const sectionsHtml = contentSections
    .map(
      (s, i) => `
    <div class="section" id="section-${i}">
      <h2>${s.title}</h2>
      <div class="section-content">${markdownToHtml(s.content)}</div>
    </div>`
    )
    .join('\n')

  const appendixLabels: Record<string, string> = {
    habitat_map: 'Habitat Map',
    species_list: 'Species List',
    photographs: 'Site Photographs',
    survey_datasheets: 'Survey Datasheets',
    desk_study_data: 'Desk Study Data',
    legislation: 'Legislation References',
  }

  const appendicesHtml =
    options.appendices.length > 0
      ? `
    <div class="section">
      <h2>Appendices</h2>
      ${options.appendices
        .map(
          (a, i) => `
        <h3>Appendix ${String.fromCharCode(65 + i)}: ${appendixLabels[a] || a}</h3>
        <p><em>[Content to be inserted]</em></p>`
        )
        .join('\n')}
    </div>`
      : ''

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${options.title}</title>
  <style>
    body {
      font-family: 'Calibri', 'Segoe UI', sans-serif;
      font-size: 11pt;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    .cover-page {
      text-align: center;
      padding: 80px 0;
      border-bottom: 2px solid #2c5234;
      margin-bottom: 40px;
    }
    .cover-page h1 {
      color: #2c5234;
      font-size: 14pt;
      text-transform: uppercase;
      letter-spacing: 2px;
      margin-bottom: 20px;
    }
    .cover-page .title {
      font-size: 22pt;
      font-weight: bold;
      margin-bottom: 30px;
    }
    .cover-page .details {
      font-size: 12pt;
      color: #666;
    }
    .cover-page .details div { margin: 5px 0; }
    .toc { margin: 40px 0; }
    .toc h2 { color: #2c5234; border-bottom: 1px solid #2c5234; padding-bottom: 5px; }
    .toc ol { padding-left: 20px; }
    .toc li { margin: 5px 0; }
    .toc a { color: #2c5234; text-decoration: none; }
    .toc a:hover { text-decoration: underline; }
    .section { margin: 30px 0; page-break-before: always; }
    .section:first-of-type { page-break-before: avoid; }
    .section h2 { color: #2c5234; border-bottom: 1px solid #ddd; padding-bottom: 5px; font-size: 14pt; }
    .section h3 { color: #444; font-size: 12pt; }
    .section-content { margin-top: 10px; }
    table { border-collapse: collapse; width: 100%; margin: 10px 0; }
    th, td { border: 1px solid #ddd; padding: 6px 10px; text-align: left; font-size: 10pt; }
    th { background: #f5f5f5; font-weight: bold; }
    ul, ol { padding-left: 25px; }
    li { margin: 3px 0; }
    .footer {
      margin-top: 40px;
      padding-top: 10px;
      border-top: 1px solid #ddd;
      font-size: 9pt;
      color: #999;
      text-align: center;
    }
    @media print {
      body { padding: 20px; }
      .section { page-break-before: always; }
    }
  </style>
</head>
<body>
  <div class="cover-page">
    <h1>Preliminary Ecological Appraisal</h1>
    <div class="title">${escapeHtml(options.title)}</div>
    <div class="details">
      <div><strong>Prepared For:</strong> ${escapeHtml(options.preparedFor || 'Client')}</div>
      <div><strong>Site Reference:</strong> ${escapeHtml(options.siteCode)}</div>
      <div><strong>Version:</strong> ${options.version}</div>
      <div><strong>Date:</strong> ${escapeHtml(options.date)}</div>
    </div>
  </div>

  <div class="toc">
    <h2>Table of Contents</h2>
    <ol>${tocHtml}</ol>
  </div>

  ${sectionsHtml}

  ${appendicesHtml}

  <div class="footer">
    Generated by Dulra Ecological Platform &mdash; ${escapeHtml(options.date)}
  </div>
</body>
</html>`
}

/** Escape HTML special characters */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/** Simple markdown to HTML converter for report content */
function markdownToHtml(md: string): string {
  let html = escapeHtml(md)

  // Bold
  html = html.replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
  html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
  html = html.replace(/\*(.*?)\*/g, '<em>$1</em>')

  // Headers (##, ###)
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>')
  html = html.replace(/^## (.+)$/gm, '<h3>$1</h3>')

  // Tables — convert markdown tables to HTML
  html = html.replace(
    /^(\|.+\|)\n(\|[\s-:|]+\|)\n((?:\|.+\|\n?)*)/gm,
    (_match, headerRow: string, _separator: string, bodyRows: string) => {
      const headers = headerRow
        .split('|')
        .filter((c: string) => c.trim())
        .map((c: string) => `<th>${c.trim()}</th>`)
        .join('')
      const rows = bodyRows
        .trim()
        .split('\n')
        .map((row: string) => {
          const cells = row
            .split('|')
            .filter((c: string) => c.trim())
            .map((c: string) => `<td>${c.trim()}</td>`)
            .join('')
          return `<tr>${cells}</tr>`
        })
        .join('')
      return `<table><thead><tr>${headers}</tr></thead><tbody>${rows}</tbody></table>`
    }
  )

  // Unordered lists
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>')
  html = html.replace(/((?:<li>.*<\/li>\n?)+)/g, '<ul>$1</ul>')

  // Ordered lists
  html = html.replace(/^\d+\.\s(.+)$/gm, '<li>$1</li>')

  // Paragraphs — wrap remaining text blocks
  html = html.replace(/\n\n/g, '</p><p>')
  html = `<p>${html}</p>`

  // Clean up empty paragraphs
  html = html.replace(/<p>\s*<\/p>/g, '')
  html = html.replace(/<p>(<h[23]>)/g, '$1')
  html = html.replace(/(<\/h[23]>)<\/p>/g, '$1')
  html = html.replace(/<p>(<table>)/g, '$1')
  html = html.replace(/(<\/table>)<\/p>/g, '$1')
  html = html.replace(/<p>(<ul>)/g, '$1')
  html = html.replace(/(<\/ul>)<\/p>/g, '$1')

  return html
}
